services:
  frontend:
    image: node:14-alpine3.16
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start

  backend:
    image: node:14-alpine3.16
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: node app.js

  db:
    build: docker/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: